# Generated by Django 4.2.28 on 2026-05-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_is_hidden_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('shipping_address', models.TextField(help_text='Adresse de livraison')),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('shipping_country', models.CharField(default='France', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En préparation'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('goal', models.CharField(choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Prise de muscle'), ('strength', 'Force'), ('endurance', 'Endurance'), ('mobility', 'Mobilité'), ('fitness', 'Remise en forme')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('duration', models.CharField(choices=[('7_days', '7 jours'), ('4_weeks', '4 semaines'), ('8_weeks', '8 semaines'), ('12_weeks', '12 semaines')], max_length=20)),
                ('description_short', models.CharField(max_length=200)),
                ('description_long', models.TextField()),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('total_sessions', models.IntegerField(default=0, help_text='Nombre total de séances')),
                ('duration_weeks', models.IntegerField(default=0, help_text='Durée en semaines')),
                ('nutrition_tips', models.TextField(blank=True, help_text='Conseils nutritionnels')),
                ('equipment_needed', models.TextField(blank=True, help_text='Matériel nécessaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Numéro du jour dans le programme')),
                ('name', models.CharField(help_text='Ex: Jour 1 - Pectoraux & Triceps', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du jour')),
                ('is_rest_day', models.BooleanField(default=False, help_text='Vrai si jour de repos')),
                ('estimated_duration_minutes', models.IntegerField(default=45, help_text='Durée estimée en minutes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.program')),
            ],
            options={
                'verbose_name': 'Jour de programme',
                'verbose_name_plural': 'Jours de programme',
                'ordering': ['day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, help_text="Ordre de l'exercice dans le jour")),
                ('sets', models.IntegerField(default=3, help_text='Nombre de séries')),
                ('reps', models.CharField(help_text='Ex: 8-12, 15, AMRAP', max_length=50)),
                ('rest_seconds', models.IntegerField(default=60, help_text='Temps de repos en secondes')),
                ('weight_note', models.CharField(blank=True, help_text='Note sur le poids (ex: 60% 1RM)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques pour cet exercice')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.programday')),
            ],
            options={
                'verbose_name': 'Exercice de programme',
                'verbose_name_plural': 'Exercices de programme',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('strength', 'Musculation'), ('cardio', 'Cardio'), ('yoga', 'Yoga & Mobilité'), ('running', 'Running'), ('clothing', 'Vêtements'), ('accessories', 'Accessoires'), ('nutrition', 'Nutrition Sportive')], max_length=20)),
                ('description_short', models.CharField(help_text='Description courte pour les cartes', max_length=200)),
                ('description_long', models.TextField(help_text='Description détaillée du produit')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en EUR', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix barré si promo', max_digits=10, null=True)),
                ('image', models.CharField(blank=True, help_text="URL de l'image principale", max_length=500, null=True)),
                ('gallery', models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images additionnelles")),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='Note moyenne sur 5', max_digits=3)),
                ('stock', models.IntegerField(default=10, help_text='Stock disponible')),
                ('brand', models.CharField(blank=True, help_text='Marque du produit', max_length=100)),
                ('features', models.JSONField(blank=True, default=list, help_text='Liste des caractéristiques')),
                ('recommended_for', models.TextField(blank=True, help_text='Pour qui ce produit est recommandé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_exercises', models.ManyToManyField(blank=True, related_name='recommended_products', to='api.exercise')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix au moment de la commande', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='UserProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='not_started', max_length=20)),
                ('current_day', models.IntegerField(default=1, help_text='Jour actuel dans le programme')),
                ('days_completed', models.JSONField(blank=True, default=list, help_text='Liste des jours complétés')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression utilisateur',
                'verbose_name_plural': 'Progressions utilisateurs',
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('exercise', 'Exercice'), ('recipe', 'Recette'), ('product', 'Produit')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes personnelles sur ce favori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.exercise')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.product')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'exercise', 'recipe', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
