# Generated by Django 4.2.28 on 2026-05-18 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cart_order_program_programday_programexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_per_minute',
            field=models.IntegerField(blank=True, help_text='Calories brûlées par minute (estimation)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions étape par étape'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Exercice polyarticulaire vs isolation'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list, help_text='Groupes musculaires secondaires sollicités'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, help_text='URL de la vidéo tutoriel', max_length=500, null=True),
        ),
    ]
