# Generated by Django 4.2.28 on 2026-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_exercise_calories_per_minute_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fiber_g',
            field=models.IntegerField(default=0, help_text='Fibres en grammes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, help_text='Nombre de portions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium_mg',
            field=models.IntegerField(default=0, help_text='Sodium en milligrammes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar_g',
            field=models.IntegerField(default=0, help_text='Sucres en grammes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags pour le filtrage (ex: vegan, gluten-free)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
